spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
#  sql:
#    init:
#      data-locations: classpath:static/db/data.sql
#      mode: always

decorator:
  datasource:
    p6spy:
      enable-logging: true

file:
  img: Img/                       # 각 이미지 파일 저장 경로

iam:
  access-key: ${IAM_ACCESS_KEY}
  secret-key: ${IAM_SECRET_KEY}
  region: ap-northeast-2

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

mod: server